# Directs the Travis CI build service for Web WorldWind
# For more information see https://docs.travis-ci.com/user/customizing-the-build/

# Set up to run the JavaScript build script per the Travis CI documentation
language: node_js

# Configure the build to use the latest Node.js 6.x release
node_js:
  - "6"

# Build the project. Travis CI automatically runs npm install before the build
script:
  - npm run build

# Node.js build cache configuration. See the Travis CI documentation: https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Caching-with-npm
cache:
  directories:
    - "node_modules"

deploy:
  # Publish to npm repository
  - provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_KEY
    skip_cleanup: true
    on:
      tags: true
  # Create CHANGELOG.md in the current directory
  - provider: script
    script: ./travis/changelog.sh >> CHANGELOG.md
    skip_cleanup: true
    on:
      tags: true
  # Create a GitHub release and publish CHANGELOG.md to the release assets
  - provider: releases
    api_key: $GITHUB_API_KEY
    file: CHANGELOG.md
    skip_cleanup: true
    on:
      tags: true
